Repository CA-G12/weather-app-Yazeed-Nader, pull requests merged in 2022-08, with the labels that each got.

#3 Completed files structure
  .gitignore
  public/index.html
  public/main.css
  public/script.js
  public/test.js
  src/.eslintrc.json
  src/handlers/city-handlers.js
  src/package-lock.json
  src/package.json
  src/router.js
  src/server.js
  src/test.js
  src/word-search.js
Labels: done

#5 Some changes on file structure, add README.md, add locations.txt
  README.md
  package-lock.json
  package.json
  src/locations.txt
Labels: done

#7 created server file and router file functionality
  .eslintrc.json
  package.json
  src/locations.txt
  src/router.js
  src/server.js
Labels: done

#9 created front end files and added their functionality
  public/index.html
  public/main.css
  public/script.js
  src/server.js
Labels: done

#12 created handlers for all routes and finished router.js
  public/index.html
  src/handlers/city-handler.js
  src/handlers/city-handlers.js
  src/handlers/home-handler.js
  src/handlers/index-handlers.js
  src/handlers/public-handler.js
  src/router.js
Labels: done

#13 Create landing page
  package.json
  public/auto-complete.js
  public/index.html
  public/main.css
  public/script.js
Labels: waiting review

#20 test code
  public/index.html
  public/searchFinction.js
Labels: Test

#21 19 fix errors router
  .eslintrc.json
  public/script.js
  public/searchFinction.js
  src/file-access.js
  src/handlers/error-handlers.js
  src/router.js
  src/test.js
Labels: done

#17 Created server tests
  .eslintrc.json
  src/handlers/error-handlers.js
  src/test.js
Labels: waiting review

#23 finished requesting suggestions when user starts typing, modified ind…
  public/auto-complete.js
  public/index.html
  public/main.css
  public/searchFinction.js
Labels: done

#26 some updates related to issue 25 and another branch, I will merge
  public/auto-complete.js
  public/fetch.js
  public/index.html
  public/main.css
  public/script.js
  public/searchFinction.js
  public/searchFunction.js
  src/file-access.js
  src/locations.json
Labels: waiting review

#27 Completed fetching and rendering week temprature for selected location
  .vscode/settings.json
  public/index.html
  public/main.css
  public/weather-search.js
  public/weather-week.js
  src/test.js
Labels: done

#34 create footer with style
  public/img/images.jpeg
  public/img/simple-background-world-map-wallpaper-3440x1440_15.jpg
  public/index.html
  public/main.css
Labels: waiting review

#36 create map section
  public/index.html
  public/main.css
  public/mapfetch.js
Labels: approved
